name: Run Selenium On GitHub Action
on:
  workflow_dispatch:
  schedule:
  # Scheduled task to automatically run the Selenium script every 3 hours
    - cron: '0 */6 * * *'
jobs:
  scrape:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed    
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  
        
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay requests selenium-wire
      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Running the Python script
        run: python Selenium-Action-IELTS.py ${{ secrets.EMAIL }} ${{ secrets.PASSWORD }} ${{ secrets.MYSITE }} ${{ secrets.FROM_EMAIL }} ${{ secrets.FROM_PWD }} ${{ secrets.TO_EMAIL }}
        
      - name: Commit and Push The Results From Python Selenium Action
        run: |
         git config user.name github-actions[bot]
         git config user.email github-actions[bot]@users.noreply.github.com
         git add -A
         git commit -m "GitHub Actions Results added"
         git push
